### ISSUE TITLE
User Stories: Create an account

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#1]
As a **User** I can **create an account** so that **I can book a class**

## Tasks
- [x] Task 1 - Install allauth so user can create an account
- [x] Task 2 - Create booking page that user can only access while logged in
- [x] Task 3 - Set up code so users booking is saved to database

**Comment by seanj06** [comment]
All tasks completed, user able to sign into account, access booking page and book a class which is saved to the database
[commit](https://github.com/seanj06/Little-Ducks-P4/commit/01250bfa8208da2fba286b4fc835307b8942e3a1)
