### ISSUE TITLE
Create new django project and app

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#10]
As a **developer** I can **create a new Django project correctly** so that **my project can be built in the correct way**

## Tasks
- [x] Task 1 - Create new django project from command line
- [x] Task 2 - Create new app inside project andadd to installed apps on settings.py
- [x] Task 3 - Migrate all changes to database
- [x] Task 4 - Run app on server to make sure it was created successfully

**Comment by seanj06** [comment]
All tasks completed and new project created successfully - [commit](https://github.com/seanj06/Little-Ducks-P4/commit/938b975d1adcc9214450da4bd94db66a1aba7ea8)
