### ISSUE TITLE
Get project ready for Heroku Deployment

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#11]
As a **developer** I can **deploy my project on Heroku** so that **it can be seen and used by other users**

## Tasks
- [x] Task 1 - Create new app on Heroku
- [x] Task 2 - Create new instance on ElephantSql dashboard
- [x] Task 3 - Create env.py file and change settings.py as required
- [x] Task 4 - Migrate changes to database
- [x] Task 5 - Add config vars on Heroku
- [x]  Task 6 - Create procfile
- [x] Task 7 - Deploy Branch in Heroku

**Comment by seanj06** [comment]
All tasks completed and project deployed to Heroku - [commit](https://github.com/seanj06/Little-Ducks-P4/commit/275c0d88f61c46058deb8bc8f15d47cdd9e6dda5)

**Comment by seanj06** [comment]
tasks completed  [commit number](https://github.com/seanj06/Little-Ducks-P4/commit/275c0d88f61c46058deb8bc8f15d47cdd9e6dda5)
