### ISSUE TITLE
 Create SuperUser for admin panel

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#5]
As a **developer** I can **create a superuser** so that **i can manage my application from the admin panel**

## Tasks
- [ ] Task 1 - Create Superuser from command line
- [ ] Task 2 - Install Summernote from command line
- [ ] Task 3 - Run project with /admin added to url to make sure superuser can login

**Comment by seanj06** [comment]
Super user created and log in panel checked.. - [commit](https://github.com/seanj06/Little-Ducks-P4/commit/728cd23e88f741c1388f5cd8dd817ff657cfd386)
