### ISSUE TITLE
Create Templates

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#6]
As a **developer** I can **create templates** so that **users can see the website online**

## Tasks
- [x] Task 1 - Create templates folder
- [x] Task 2 - Create base.html file to hold base template code
- [x] Task 3 - Create base html template code
- [x] Task 4 - Create news urls.py file and enter new path

**Comment by seanj06** [comment]
Templates made for app - [commit](https://github.com/seanj06/Little-Ducks-P4/commit/808a6a2f66cae22700b262f60e6cbd46c2ea4302)
