### ISSUE TITLE
Add Database Models

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#8]
As a **developer** I can **add database models** so that **the database knows how to handle user data**

## Tasks
- [x] Task 1 - Import appropriate librarys at top of models.py file
- [x] Task 2 - Create a class based model
- [x] Task 3 - Add meta class to class based model
- [x] Task 4 - MIgrate changes to database

**Comment by seanj06** [comment]
Booking model completed [commit](https://github.com/seanj06/Little-Ducks-P4/commit/fe9b1c4155e790f61ad35149939fbed57159b93d)
