### ISSUE TITLE
Initial Django project setup

### ISSUE THREAD

**Issue by seanj06** [seanj06/Little-Ducks-P4#9]
As a **developer** I can **install the needed librarys and packages** so that **my project is set up correctly**

## Tasks
- [x] Task 1 - Install Django + Heroku server from command line
- [x] Task 2 - Install PostgreSql database from command line
- [x] Task 3 - Install Cloudinary from command line
- [x] Task 4 - Create requirements.txt file

**Comment by seanj06** [comment]
All tasks completed and neccessary libraries installed - [commit](https://github.com/seanj06/Little-Ducks-P4/commit/8675a5f4cb6ea2172afb595139f360bd4170d3ec)
